// <auto-generated />
using System;
using LibraryManager.API;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LibraryManager.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250729085531_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LibraryManager.API.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Fernando Pessoa"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Hernandes Dias Lopes"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Reinhard Bonnke"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Jane Austen"
                        },
                        new
                        {
                            Id = 5,
                            Name = "George Orwell"
                        });
                });

            modelBuilder.Entity("LibraryManager.API.Models.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AuthorId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsBorrowed")
                        .HasColumnType("boolean");

                    b.Property<int>("PublisherId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("PublisherId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b1d8b2dd-2d77-4b42-9dc6-7f4c1ec4c001"),
                            AuthorId = 1,
                            IsBorrowed = false,
                            PublisherId = 1,
                            Title = "The Book of Disquiet"
                        },
                        new
                        {
                            Id = new Guid("b1d8b2dd-2d77-4b42-9dc6-7f4c1ec4c002"),
                            AuthorId = 1,
                            IsBorrowed = false,
                            PublisherId = 1,
                            Title = "Message"
                        },
                        new
                        {
                            Id = new Guid("b1d8b2dd-2d77-4b42-9dc6-7f4c1ec4c003"),
                            AuthorId = 1,
                            IsBorrowed = false,
                            PublisherId = 1,
                            Title = "Poesias Ineditas"
                        },
                        new
                        {
                            Id = new Guid("b1d8b2dd-2d77-4b42-9dc6-7f4c1ec4c004"),
                            AuthorId = 2,
                            IsBorrowed = false,
                            PublisherId = 2,
                            Title = "O Deus que Destrona Deuses"
                        },
                        new
                        {
                            Id = new Guid("b1d8b2dd-2d77-4b42-9dc6-7f4c1ec4c005"),
                            AuthorId = 2,
                            IsBorrowed = false,
                            PublisherId = 2,
                            Title = "Jesus Cristo: O Deus Filho"
                        },
                        new
                        {
                            Id = new Guid("b1d8b2dd-2d77-4b42-9dc6-7f4c1ec4c006"),
                            AuthorId = 3,
                            IsBorrowed = false,
                            PublisherId = 3,
                            Title = "Avivamento"
                        },
                        new
                        {
                            Id = new Guid("b1d8b2dd-2d77-4b42-9dc6-7f4c1ec4c007"),
                            AuthorId = 3,
                            IsBorrowed = false,
                            PublisherId = 3,
                            Title = "Living a Life of Fire"
                        },
                        new
                        {
                            Id = new Guid("b1d8b2dd-2d77-4b42-9dc6-7f4c1ec4c008"),
                            AuthorId = 4,
                            IsBorrowed = false,
                            PublisherId = 4,
                            Title = "Pride and Prejudice"
                        },
                        new
                        {
                            Id = new Guid("b1d8b2dd-2d77-4b42-9dc6-7f4c1ec4c009"),
                            AuthorId = 4,
                            IsBorrowed = false,
                            PublisherId = 4,
                            Title = "Sense and Sensibility"
                        },
                        new
                        {
                            Id = new Guid("b1d8b2dd-2d77-4b42-9dc6-7f4c1ec4c00a"),
                            AuthorId = 4,
                            IsBorrowed = false,
                            PublisherId = 4,
                            Title = "Emma"
                        },
                        new
                        {
                            Id = new Guid("b1d8b2dd-2d77-4b42-9dc6-7f4c1ec4c00b"),
                            AuthorId = 4,
                            IsBorrowed = false,
                            PublisherId = 4,
                            Title = "Persuasion"
                        },
                        new
                        {
                            Id = new Guid("b1d8b2dd-2d77-4b42-9dc6-7f4c1ec4c00c"),
                            AuthorId = 5,
                            IsBorrowed = false,
                            PublisherId = 4,
                            Title = "1984"
                        },
                        new
                        {
                            Id = new Guid("b1d8b2dd-2d77-4b42-9dc6-7f4c1ec4c00d"),
                            AuthorId = 5,
                            IsBorrowed = false,
                            PublisherId = 4,
                            Title = "Animal Farm"
                        },
                        new
                        {
                            Id = new Guid("b1d8b2dd-2d77-4b42-9dc6-7f4c1ec4c00e"),
                            AuthorId = 5,
                            IsBorrowed = false,
                            PublisherId = 4,
                            Title = "Homage to Catalonia"
                        },
                        new
                        {
                            Id = new Guid("b1d8b2dd-2d77-4b42-9dc6-7f4c1ec4c00f"),
                            AuthorId = 5,
                            IsBorrowed = false,
                            PublisherId = 4,
                            Title = "A Clergyman's Daughter"
                        });
                });

            modelBuilder.Entity("LibraryManager.API.Models.Publisher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Publishers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Porto Editora"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Hagnos"
                        },
                        new
                        {
                            Id = 3,
                            Name = "CPAD"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Penguin Classics"
                        });
                });

            modelBuilder.Entity("LibraryManager.API.Models.Book", b =>
                {
                    b.HasOne("LibraryManager.API.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryManager.API.Models.Publisher", "Publisher")
                        .WithMany("Books")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("LibraryManager.API.Models.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("LibraryManager.API.Models.Publisher", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
